#!/usr/bin/env python3
"""Generate the montech-hyperflow icon set.

Run:  python3 packaging/icons/generate.py

Two axes, because one drawing cannot cover both:

* SIZE. The full drawing -- octagon, CPU label, ten-segment bar, two
  seven-segment digits, unit mark -- is unreadable below about 32px. A
  reduced drawing is emitted into the 16x16 and 24x24 theme directories and
  the full one into scalable/, and the icon theme picks by requested size.

* PANEL COLOUR. The pump head is a dark object. On a dark panel its body
  disappears and only the rim reads, so the rim is lightened; on a light
  panel the body reads as a solid mass and the rim is darkened to stay crisp.
  There is no freedesktop convention for this, so the tray chooses the name
  at runtime: "-light" suffixed icons are for light panels.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

# the real head, sampled from the vendor manual's render
BODY = "#23262d"
SCREEN = "#0b0d11"
DIGIT = "#f2f4f8"
LABEL = "#4da3ff"
UNIT = "#4ad07a"
BAR = ["#f0b429", "#f0a52a", "#ef972c", "#ee882e", "#ed7830",
       "#ec6733", "#ea5535", "#e84338", "#e6323b", "#e4213e"]
OFF = "#333845"

RIM_ON_DARK = "#7c8598"     # lifted, so the silhouette separates from a dark panel
RIM_ON_LIGHT = "#171a20"    # darkened, so the edge stays crisp on a light panel

SEG = {"0": "abcdef", "1": "bc", "2": "abged", "3": "abgcd", "4": "fbgc",
       "5": "afgcd", "6": "afgedc", "7": "abc", "8": "abcdefg", "9": "abfgcd"}


def octagon(size, cut, inset=0.0):
    s, c, i = size, cut, inset
    pts = [(c + i, i), (s - c - i, i), (s - i, c + i), (s - i, s - c - i),
           (s - c - i, s - i), (c + i, s - i), (i, s - c - i), (i, c + i)]
    return "M" + " L".join("%.2f %.2f" % p for p in pts) + " Z"


def digit(ch, x, y, w, h, t, fill):
    segs = SEG[ch]
    mid = y + (h - t) / 2.0
    vh = (h - t) / 2.0 + t
    r = t / 2.0
    out = []

    def rect(rx, ry, rw, rh):
        out.append('<rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" '
                   'rx="%.2f" fill="%s"/>' % (rx, ry, rw, rh, r, fill))
    if "a" in segs: rect(x, y, w, t)
    if "g" in segs: rect(x, mid, w, t)
    if "d" in segs: rect(x, y + h - t, w, t)
    if "f" in segs: rect(x, y, t, vh)
    if "b" in segs: rect(x + w - t, y, t, vh)
    if "e" in segs: rect(x, mid, t, vh)
    if "c" in segs: rect(x + w - t, mid, t, vh)
    return "".join(out)


def detailed(rim, lit):
    """48px drawing: everything the real head shows.

    Proportions follow the product: the octagon IS the dark glass face, edge
    to edge, with a thin bright rim -- not a chunky body with a small window
    cut in it. That is what makes it read as this cooler.
    """
    bar = "".join(
        '<rect x="9.4" y="%.2f" width="3.4" height="1.5" rx="0.55" fill="%s"/>'
        % (33.0 - i * 2.05, (c if lit else OFF)) for i, c in enumerate(BAR))
    dig = DIGIT if lit else OFF
    return '''<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
  <!-- Generated by packaging/icons/generate.py - do not edit by hand.
       The Montech HyperFlow Digital pump head drawn from the product's own geometry:
       an octagonal glass face edge to edge, a thin rim, a ten-segment level
       bar and two seven-segment digits. No vendor artwork is reproduced. -->
  <path d="%s" fill="%s"/>
  <path d="%s" fill="none" stroke="%s" stroke-width="2.2"/>
  <text x="25.5" y="15.6" font-family="DejaVu Sans, sans-serif" font-size="6.0"
        font-weight="bold" fill="%s" letter-spacing="0.5">CPU</text>
  %s
  %s%s
  <text x="38.2" y="34.4" font-family="DejaVu Sans, sans-serif" font-size="5.0"
        font-weight="bold" fill="%s">°C</text>
</svg>
''' % (octagon(48, 13.5, 1.6), SCREEN, octagon(48, 13.5, 1.6), rim,
       (LABEL if lit else OFF), bar,
       digit("4", 16.4, 17.6, 9.4, 17.0, 2.7, dig),
       digit("2", 28.4, 17.6, 9.4, 17.0, 2.7, dig),
       (UNIT if lit else OFF))


def compact(rim, lit):
    """16px drawing: the same object, reduced to what survives at 16px.

    Same edge-to-edge glass face. The CPU label, the unit mark and six of the
    ten bar segments are gone, and two solid blocks stand in for the digits:
    at 16px an actual "42" is a smudge, and a smudge reads as a defect rather
    than as a number.
    """
    segs = "".join(
        '<rect x="3.15" y="%.2f" width="1.7" height="1.0" rx="0.35" fill="%s"/>'
        % (10.5 - i * 1.45, (c if lit else OFF))
        for i, c in enumerate([BAR[1], BAR[4], BAR[7], BAR[9]]))
    dig = DIGIT if lit else OFF
    return '''<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
  <!-- Generated by packaging/icons/generate.py - do not edit by hand.
       Reduced drawing for 16-24px: the octagonal glass face edge to edge,
       four bar segments and two digit blocks. Anything finer turns to mush. -->
  <path d="%s" fill="%s"/>
  <path d="%s" fill="none" stroke="%s" stroke-width="1.15"/>
  %s
  <rect x="6.1" y="4.6" width="3.4" height="6.8" rx="0.6" fill="%s"/>
  <rect x="10.3" y="4.6" width="3.4" height="6.8" rx="0.6" fill="%s"/>
</svg>
''' % (octagon(16, 4.5, 0.6), SCREEN, octagon(16, 4.5, 0.6), rim,
       segs, dig, dig)


VARIANTS = [
    ("montech-hyperflow", RIM_ON_DARK, True),
    ("montech-hyperflow-idle", RIM_ON_DARK, False),
    ("montech-hyperflow-light", RIM_ON_LIGHT, True),
    ("montech-hyperflow-light-idle", RIM_ON_LIGHT, False),
]

HDR = '<?xml version="1.0" encoding="UTF-8"?>\n'


def main():
    written = []
    for name, rim, lit in VARIANTS:
        for subdir, draw in (("16x16/apps", compact),
                             ("24x24/apps", compact),
                             ("scalable/apps", detailed)):
            d = os.path.join(HERE, subdir)
            os.makedirs(d, exist_ok=True)
            path = os.path.join(d, name + ".svg")
            with open(path, "w") as fh:
                fh.write(HDR + draw(rim, lit))
            written.append(path)
    for path in written:
        print(os.path.relpath(path, os.path.dirname(HERE)))
    print("%d files" % len(written))


if __name__ == "__main__":
    main()
